apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/kernel-planckster
  - ../base/websat-planckster
patchesStrategicMerge:
  - ./patch-kernel-planckster.yaml
  - ./patch-websat-planckster.yaml
