---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-operator
  namespace: minio
spec:
  values:
    nodeSelector:
      key: "kubernetes.io/hostname"
      value: "sda-worker-03"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: minio-prod
spec:
  values:
    pools:
      - name: prod-pool
        nodeSelector:
          key: "kubernetes.io/hostname"
          value: "sda-worker-03"
    