apiVersion: apps/v1
kind: Deployment
metadata:
  name: websat-planckster
  namespace: sda
  labels:
    ch.dadai.service: websat-planckster
spec:
  replicas: 2
  selector:
    matchLabels:
      ch.dadai.service: websat-planckster
  template:
    metadata:
      labels:
        ch.dadai.service: websat-planckster
    spec:
      containers:
        - name: websat-planckster
          image: maany/websat-planckster:1.0.0-beta
          imagePullPolicy: Always
          env:
            - name: NEXTAUTH_URL
              value: "https://websat-planckster.devmaany.com" # TODO: patch in production
            # - name: HOSTNAME
            #   value: "localhost" # TODO: patch in production
            - name: KP_CLIENT_ID
              value: "1"
          resources:
            limits:
              memory: "512Mi"
              cpu: "100m"
            requests:
              memory: "256Mi"
              cpu: "100m"
