apiVersion: apps/v1
kind: Deployment
metadata:
  name: kernel-planckster
  namespace: sda
  labels:
    ch.dadai.service: kernel-planckster
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      ch.dadai.service: kernel-planckster
  template:
    metadata:
      labels:
        ch.dadai.service: kernel-planckster
    spec:
      nodeSelector:
          kubernetes.io/hostname: "sda-worker-03"
      containers:
        - name: kernel-planckster
          image: maany/kernel-planckster:2.0.2
          env:
            - name: KP_ALLOWED_ORIGINS
              value: "*.cluster.local, *.devmaany.com"
            - name: KP_FASTAPI_WORKERS
              value: "4"
            - name: KP_OBJECT_STORE_HOST
              value: "sda-minio.devmaany.com"
            - name: KP_OBJECT_STORE_PORT
              value: "443"
            - name: KP_OBJECT_STORE_SECURE
              value: "true"
          resources:
            limits:
              memory: "6Gi"
              cpu: "3000m"
            requests:
              memory: "4Gi"
              cpu: "3000m"

