---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-prod
  namespace: minio-prod
spec:
  values:
    nodeSelector:
      kubernetes.io/hostname: sda-worker-03
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: minio-prod
spec:
  values:
    pools:
      - name: prod-pool
        nodeSelector:
          kubernetes.io/hostname: sda-worker-03
    