apiVersion: apps/v1
kind: Deployment
metadata:
  name: kernel-planckster
  namespace: sda
  labels:
    ch.dadai.service: kernel-planckster
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      ch.dadai.service: kernel-planckster
  template:
    metadata:
      labels:
        ch.dadai.service: kernel-planckster
    spec:
      containers:
        - name: kernel-planckster
          image: maany/kernel-planckster:1.0.0-alpha
          env:
            - name: KP_ALLOWED_ORIGINS
              value: "*.cluster.local, *.devmaany.com"
          resources:
            limits:
              memory: "256Mi"
              cpu: "100m"
            requests:
              memory: "256Mi"
              cpu: "100m"

