apiVersion: apps/v1
kind: Deployment
metadata:
  name: websat-planckster
  namespace: sda
  labels:
    ch.dadai.service: websat-planckster
spec:
  replicas: 2
  selector:
    matchLabels:
      ch.dadai.service: websat-planckster
  template:
    metadata:
      labels:
        ch.dadai.service: websat-planckster
    spec:
      containers:
        - name: websat-planckster
          image: maany/websat-planckster:2.0.0-rc.1
          imagePullPolicy: Always
          env:
            - name: NEXTAUTH_URL
              value: "https://sda.devmaany.com" # TODO: patch in production
            # - name: HOSTNAME
            #   value: "localhost" # TODO: patch in production
            - name: KP_CLIENT_ID
              value: "1"
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
            requests:
              memory: "1Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: websat-planckster
  namespace: sda
  labels:
    ch.dadai.service: websat-planckster
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    ch.dadai.service: websat-planckster
