apiVersion: apps/v1
kind: Deployment
metadata:
  name: kernel-planckster
  namespace: sda
  labels:
    ch.dadai.service: kernel-planckster
spec:
  replicas: 5
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      ch.dadai.service: kernel-planckster
  template:
    metadata:
      labels:
        ch.dadai.service: kernel-planckster
    spec:
      containers:
        - name: kernel-planckster
          image: maany/kernel-planckster:1.0.0-alpha
          env:
            - name: KP_ALLOWED_ORIGINS
              value: "*.sda.svc.cluster.local, sda.mpi-sws.org, *.cluster.local"
          resources:
            limits:
              cpu: "4"
              memory: "8Gi"
            requests:
              cpu: "1"
              memory: "2Gi"
