apiVersion: apps/v1
kind: Deployment
metadata:
  name: websat-planckster
  namespace: sda
  labels:
    ch.dadai.service: websat-planckster
spec:
  replicas: 1
  selector:
    matchLabels:
      ch.dadai.service: websat-planckster
  template:
    metadata:
      labels:
        ch.dadai.service: websat-planckster
    spec:
      containers:
        - name: websat-planckster
          image: maany/websat-planckster:2.3.0
          imagePullPolicy: Always
          env:
            - name: NEXTAUTH_URL
              value: "https://sda.devmaany.com" # TODO: patch in production
            - name: NEXT_PUBLIC_APP_URL
              value: "https://sda.devmaany.com" # TODO: patch in production
            - name: KP_CLIENT_ID
              value: "1"
          resources:
            limits:
              memory: "2Gi"
              cpu: "3000m"
            requests:
              memory: "2Gi"
              cpu: "2500m"
---
apiVersion: v1
kind: Service
metadata:
  name: websat-planckster
  namespace: sda
  labels:
    ch.dadai.service: websat-planckster
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    ch.dadai.service: websat-planckster
