version: "3"
services:
    minio:
        image: quay.io/minio/minio:latest
        container_name: minio
        restart: always
        ports:
            - "9000:9000"
            - "9090:9090"
        env_file:
            - ./minio/.env
        volumes:
            - ./minio/data:/data
            - ./minio/config:/root/.minio
        command: server /data --console-address ":9090"
    db:
        image: postgres
        restart: always
        container_name: kp-db
        env_file:
            - ./kernel-planckster/.env
        volumes:
            - ./kernel-planckster/postgres-data:/var/lib/postgresql/data
        ports:
        - 5432:5432
    adminer:
        image: adminer
        container_name: kp-adminer
        restart: always
        ports:
        - 8080:8080