apiVersion: apps/v1
kind: Deployment
metadata:
  name: swissgrid-predictor
  namespace: sda
  labels:
    ch.dadai.service: swissgrid-predictor
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      ch.dadai.service: swissgrid-predictor
  template:
    metadata:
      labels:
        ch.dadai.service: swissgrid-predictor
    spec:
      containers:
        - name: swissgrid-predictor
          image: maany/mpi-sda-swissgrid-predictor:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          env:
            - name: KP_HOST
              value: "kernel-planckster.sda.svc.cluster.local"
            - name: KP_PORT
              value: "8000"
            - name: KP_SCHEME
              value: "http"
            - name: KP_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: kp-auth-token
                  key: kp_auth_token
            
      restartPolicy: Always
