apiVersion: v1
kind: Service
metadata:
  labels:
    ch.dadai.service: swissgrid-predictor
  name: swissgrid-predictor
  namespace: sda
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 5000
  selector:
    ch.dadai.service: swissgrid-predictor