apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
    - ./secrets
    - ./bitnami
    - ./postgres
    - ./minio
    - ./kernel-planckster
    - ./websat-planckster
    - ./mpi-sda-swissgrid-predictor
