apiVersion: v1
kind: Service
metadata:
  labels:
    ch.dadai.service: websat-planckster
  name: websat-planckster
  namespace: sda
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    ch.dadai.service: websat-planckster