---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-tenant
  namespace: minio-operator
spec:
  chart:
    spec:
      chart: tenant
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minio
      version: 6.0.4
  interval: 1m0s
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  values:
    configuration:
      name: minio-secret



  