---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio-prod
  namespace: minio-prod
spec:
  chart:
    spec:
      chart: operator
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: minio
      version: 7.0.0
  interval: 1m0s
  install:
    disableWait: true
    skipCRDs: true
  values:
  