apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  annotations:
    kompose.cmd: kompose convert --profile storage
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: adminer
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --profile storage
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/kustomize-default: "true"
        io.kompose.service: adminer
    spec:
      containers:
        - image: adminer
          name: kp-adminer
          ports:
            - containerPort: 8080
              hostPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: "0.5"
              memory: "512Mi"
            requests:
              cpu: "0.1"
              memory: "128Mi"
      restartPolicy: Always

