apiVersion: v1
kind: Secret
metadata:
    name: kp-auth-token
    namespace: sda
type: Opaque
stringData:
    kp_auth_token: ENC[AES256_GCM,data:RDathXiGqA==,iv:8gO8cpjqxx3Q/2HPlRWfT9ti6bxcXbQfjqHZmB+ILxc=,tag:8vinDZ/34/fjDXYFud9YNw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xkz3rtp7pu0vzxmzqq2qd5reh0e4v328764re7vtj547yxls3zqgv6mp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0ajB3VUZ1THFKUHBWNStY
            Z3F3bk5oWE5VOVhQOGxJVzlSSC9rL1NMWUE0CmF3eTlOOHZLc2VsRTF1NEgvU3V6
            eTV2dXBLMzB5RXA2S0Z6WGFWeWMzTGcKLS0tIGw0NWVSTisveDZ4Vk9oc3VuOU1G
            ank2ZkU3aVpucndXNmVORkpyNnpKNEUKqhUnLv0aqeJZQCYu3vYjnkA78IYOtIzC
            0imSyW/Cn9ypUDTKpKm+XUk4RKfDeomoAJzFCCC1Z//bm6XvYUg1Hw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-13T12:02:23Z"
    mac: ENC[AES256_GCM,data:BO+m7i9ALvTs1z6eu5Me3mJBkYybWDquxkmhg+r2VR5TCNCL92Fy3xLiynTmHZPyHIChFigmP69Cx5CtBRPlK0m1QfzeFyTK0O9NruUNfWnIDlMYGZoD7lzP4SqZHdZG1rDnApS64fHtyTYfnsidFDe+O3kBaRSwKiaI+ta3Mw4=,iv:u/apGp0xAnDnAB5EMZO17zuicZgI0W768H7c5dvPUYA=,tag:u9fZan9NT/Igeolbo1SOPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
