apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
    namespace: minio-operator
type: Opaque
stringData:
    config.env: ENC[AES256_GCM,data:aqnifh6XKoVwCH7hL7scIFeqqHYuwgVlATcDTVZPRvpR9F1IYfL+wdTKlGfgU+/IYxgvLwbB1TMIeMhBNUUlVap/46UyJ0JaTNcaV7JsgQ==,iv:4kRgsdL9JzyGL5MNnJomlfcVO17u5eS95+hMTzgbjOc=,tag:1Zc9scYQWZMhcnj8kG1ZYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xkz3rtp7pu0vzxmzqq2qd5reh0e4v328764re7vtj547yxls3zqgv6mp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaTFXYkJpL2EwNGlPay9z
            Nll6UWZJRXNaNnVtcUhOdGlVb25vWmlFMzNNCkQwaHNNWkxwanlPMEg4a0d3WFdr
            WWhTZ0RCOHJHczM5OWYrU3BVQ2xqVzAKLS0tIGpHdlhXanBhdkVvWUlwOFlleWNM
            MUdUallqbmJYVjc5VkVUNExZdHFtd1UKFGm0bfeJMzMK2wX22HCQfE6B/5cFhfU6
            /QKclJfO7nADBpkKLkuFfXttOrQClzQmBKQno1KetbB4mKoCNGJkPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-01T00:19:31Z"
    mac: ENC[AES256_GCM,data:kQ8U+iVG8hv9uyxMwc0YQZ6fZe/c/R+48ye3OaCaAr6DdZc0s+otK0q1vJyatcpo0BGB6YU8E1AfIbgXjDq+SjQIPAoEy6qN1gB0pg9+GqFo79nzuA5nvJ8FC/mpugQpMx5prek5odX2lMQqPcMI/JY1f/sXhpE3FDeDcO+aVzY=,iv:nMUgoFa7/6QqTRsG6Cbjf83VP2wgidcbO8J3N+/oERk=,tag:J3OU+NMerZ9sX+LmbCx6/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
