apiVersion: v1
kind: Secret
metadata:
    name: websat-openai-secret
    namespace: sda
type: Opaque
stringData:
    apikey: ENC[AES256_GCM,data:4Xu83VdwiGZ0/7mZ,iv:JBKCLE+uh4QpwPnV1yfvw5Jz/Hll0/E1gZ+NYsOsjjI=,tag:Z2hVlj5rHDVD7UdaRqLXFw==,type:str]
    assistantid: ENC[AES256_GCM,data:tWeY/aoCPe616Gz9QhiBi1g=,iv:XdI2Fse2suUjAfuOqVrVsEW/V6SYmT8NCBAsaw+N4JA=,tag:xUOZ1D2NEf0lzg6AB3plHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age19xkz3rtp7pu0vzxmzqq2qd5reh0e4v328764re7vtj547yxls3zqgv6mp3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4aWJkeU1MZ1gwNXQwcFhT
            Z3dHZ1BHblBCQjZ5cHdlYjV3bG10dmZmSDB3Cmd6RnJJN3UrOFF1dEpCem1DTGNx
            VkNvMEhZOWhOc2RORmFiSEFEOFoxU0kKLS0tIDNxcDhyM29JYUJkbjY1L0dVc2V5
            WnMyUUVrZmx3amY4Q2tWTkZ3Y0dkaXMKDxEdX77hrZ63EDa3e/cKclH1foxK/LT/
            50cFMBPE1ENaUWUVsDv1NOjNIY1AhUdjUN8mHLW9bY3tl0E83WN41Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-13T12:02:23Z"
    mac: ENC[AES256_GCM,data:Nt3mxk6/IF8tOOwHy2tMpdn5+PsZ79KXQU5e2TjqQ+i/0Mfj0HtDiiE3LLY1mY5v52pqQUTxEcx5LEklCY8+dHOCeZa18MeHZSEraq8Vi4lEFFsJF8xDXR3QKF77Zbm6BH+zrdJEf01R0MCdsfPQgtLY2TcsZgbk55LTZFysASY=,iv:k9DgIzL+F3rDeW/Ns/yR6QfK1zAz4sOP4wiW1OWLfPI=,tag:pkYIUWm8M7XDlHHI+k6fzw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
